name: Scrape and Email Workflow

on:
  schedule:
    - cron:  '55 5 * * *'
  workflow_dispatch:


jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libxss1 libasound2 libx11-xcb1 libxrandr2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0
          wget --quiet --output-document=google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
          rm google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: npm install

      - name: Run scrape and email script
        env: # Set the environment variables using the secrets you added to GitHub
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node index.js # Replace with the path to your script if different
