name: Scrape and Email Workflow

on:
  schedule:
    # Runs at 8 AM UTC every day. You can adjust the cron schedule as needed.
    - cron:  '*/2 * * * *'
  workflow_dispatch:


jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run scrape and email script
        env: # Set the environment variables using the secrets you added to GitHub
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node index.js # Replace with the path to your script if different
